global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "Prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "Raizes-cearenses-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["raizes-cearenses-api:8080"]