# .github/workflows/build-api.yml
name: Build and Push API Docker Image

on:
  push:
    branches: [ "main" ] # Roda quando houver push na branch main
    paths:
      - 'apps/api/**'
      - 'packages/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permissão para fazer push no GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Contexto na raiz do monorepo
          file: ./apps/api/Dockerfile # Caminho para o Dockerfile da API
          push: true
          tags: ghcr.io/${{ github.repository }}/api:latest,ghcr.io/${{ github.repository }}/api:${{ github.sha }}
