name: CI (light)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Note
        run: |
          echo "Skipping builds and deploys here. Frontend is built on Vercel."


